CI: remove C++11 flag for all systems.
Both CSXCAD and openEMS subprojects now have "set(CMAKE_CXX_STANDARD 11)"
in CMakeFiles.txt. The C++11 flags are no longer necessary. If the
"./update_openEMS.sh" build process fails without manually specifying
the C++11 flag, it should be considered a bug.

In fact, passing "-std=c++11" is not just useless, but harmful. If an
older GCC version (e.g. GCC 4.8/5/6) is used, the following error would
occur:

    /usr/include/boost/math/constants/constants.hpp: In static member
    function 'static constexpr T boost::math::constants::detail::constant_half<T>
    ::get(const mpl_::int_<5>&)':
    /usr/include/boost/math/constants/constants.hpp:252:3: error: unable to
    find numeric literal operator 'operator"" Q'
       BOOST_DEFINE_MATH_CONSTANT(half, 5.000000000000000000000000000000000000e-01, "5.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e-01")

This is a known Boost/GCC issue. According to [1], because CMake
is adding "-std=gnu++11" (following "set(CMAKE_CXX_STANDARD 11)"),
while the user is also manually setting "std=c++11" in "CXXFLAGS",
GCC is put into an inconsistent state. As a result, Boost believed
"__float128" support is turned on when it's actually not.

We also update documentation to warn users to remove any manual
"-std=c++11" flags.

[1] https://github.com/boostorg/math/issues/272

Signed-off-by: Yifeng Li <tomli@tomli.me>